language: node_js
node_js:
  - 10
script:
  - yarn run build --prod

deploy:
  - provider: pages
    local_dir: www
    skip_cleanup: true
    keep-history: true
    github_token: $GH_TOKEN
    on:
      branch: master
      repo: eboukamza/image-only
