language: node_js
node_js:
  - 10
script:
  - yarn test:ci && yarn build --prod --base-href /image-only/

deploy:
  - provider: pages
    local_dir: dist
    skip_cleanup: true
    keep-history: true
    github_token: $GH_TOKEN
    on:
      branch: master
      repo: eboukamza/image-only
