version: 2

node: &node
  working_directory: ~/image-only
  docker:
    - image: cimg/node:16.13-browsers

aliases:
  - &restore_cache
    restore_cache:
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}

jobs:
  install:
    <<: *node
    steps:
      - checkout
      - *restore_cache
      - run: yarn install --frozen-lockfile
      - run: yarn audit
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
  test:
    <<: *node
    steps:
      - checkout
      - *restore_cache
      - run: yarn test --ci --coverage
  lint:
    <<: *node
    steps:
      - checkout
      - *restore_cache
      - run: yarn lint
  build:
    <<: *node
    steps:
      - checkout
      - *restore_cache
      - run: yarn build --configuration production --base-href /image-only/
      - persist_to_workspace:
          root: ~/image-only
          paths:
            - dist
  deploy:
    <<: *node
    steps:
      - checkout
      - attach_workspace:
          at: ~/image-only
      - run: ls dist

workflows:
  version: 2
  build:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
            - test
            - lint
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
